const HTTP_RESPONSE_STATUS_CODES = {
  UNPROCESSABLE_CONTENT: 422,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  OK: 200,
  BAD_GATEWAY: 502,
  BAD_REQUEST: 400,
  FORBIDDEN: 403
}

export default HTTP_RESPONSE_STATUS_CODES
